import '../models/link_model.dart';

List<LinkModel> linkModels = [
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
  LinkModel(
      id: "id",
      created: DateTime.now(),
      clickCount: 83278,
      longUrl: "https://github.com/SpielerEinzig/Mylinks/blob/main/",
      qrCode: "",
      shorUrl: "https://github.com/SpielerEinzig/Mylinks/"),
];
